### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by nickclasener** [reinink/client-side-rendering-in-laravel#5]
I cloned the app
and got a problem with building it.
`npm run dev`

Solved it by using the removed [package-lock.json](https://github.com/reinink/client-side-rendering-in-laravel/commit/a17a56f09bd9808d65ab0ae1e0aa58ca2553e0b2)

**Comment by reinink** [comment]
Yup. Whenever you run into issues with npm, delete the lock file, delete the node modules folder, and start over.

See the [Laravel Mix docs](https://laravel-mix.com/docs/4.0/troubleshooting) for full instructions. :)
