### ISSUE TITLE
This is Amazing!!!!!

### ISSUE THREAD

**Issue by trevorgreenleaf** [reinink/client-side-rendering-in-laravel#6]
I read your blog post. Such a great idea, very excited to try this on some projects.

**Comment by sarfraznawaz2005** [comment]
Me too, I think this idea can be wrapped into some package of its own.

**Comment by reinink** [comment]
Thanks @trevorgreenleaf and @sarfraznawaz2005! Glad you like it.

I am working on taking this idea to the [next level](https://twitter.com/reinink/status/1096141844373741570), and I'm developing a package for that.

Stay tuned. 😎
