### ISSUE TITLE
Page Transitions

### ISSUE THREAD

**Issue by JamiesonRoberts** [reinink/client-side-rendering-in-laravel#9]
Having read up on Turbolinks I know that page transitions are not something that it does well, but I'm also struggling to think of a way to handle page transitions with the way the rest of this is structured.

Do you have an ideas? I'm trying this out for a personal app, but I haven't been able to crack that yet.

Cheers!

**Comment by reinink** [comment]
So the challenge with using Turbolinks is that Vue is destroyed and recreated on each page load. That said, you should be able to use cloaking and transitions to do this.

```vue
<transition name="fade" appear>
    <slot />
</transition>
```

I haven't tried though, sorry, so you'll have to hack on it and see.

Good luck! 👍
